name: Build and Package Artifacts
on:
  pull_request:
  push:
    tags:
      - v*.*.*
jobs:
  build_and_package:
    name: Build and Package
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.4,17.5)"
      - name: Cache Dependency artifacts
        id: cache_dependency_artifacts
        uses: actions/cache@v3
        with:
          path: libs
          key: dependency-artifacts-${{ hashFiles('tools/setup.ps1') }}
      - name: Download Dependency artifacts
        if: steps.cache_dependency_artifacts.outputs.cache-hit != 'true'
        run: ./tools/setup.ps1
        shell: powershell
      - name: Build
        run: MSBuild kasaibox.vcxproj /t:build /p:Configuration=Release /p:Platform=Win32
        shell: powershell
      - name: Package
        run: ./tools/package.sh
        shell: bash
      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: kasaibox
          path: kasaibox
      - name: Compress Artifact
        if: github.event_name == 'push'
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: kasaibox.zip
          path: kasaibox
      - name: Publish Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kasaibox.zip
          prerelease: true
          generate_release_notes: true
